// Code generated by coz. DO NOT EDIT.
/**
 * Mongo driver for the-db
 * @module the-driver-mongo
 */
'use strict'

import TheDriverMongo from './TheDriverMongo'
import create from './create'
import mixins from './mixins'

export {
  TheDriverMongo,
  create,
  mixins,
}

export default create
