// Code generated by coz. DO NOT EDIT.
/**
 * Mongo driver for the-db
 * @module the-driver-mongo
 */
'use strict'

const _d = (m) => 'default' in m ? m.default : m

module.exports = {
  get MongoDriver () { return _d(require('./MongoDriver')) },
  get create () { return _d(require('./create')) },
  get mixins () { return _d(require('./mixins')) },
  get default () { return _d(require('./create')) },
}
