// Code generated by coz. DO NOT EDIT.
/**
 * 
 * @module mixins
 */
'use strict'

const _d = (m) => 'default' in m ? m.default : m

module.exports = {
  get mongoMix () { return _d(require('./mongoMix')) },
}
